name: siks_missing
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - scipy
  - sklearn
  - statsmodels
  - prophet
  - missforest
